### ISSUE TITLE
Problem after I use my own dataset

### ISSUE THREAD

**Issue by haprine** [johncai117/DAMSL#8]
Thanks for your interesting work! I wonder what should I do if I want to replace the CropDisease with my own dataset? I met the problem that the output of __len__() was 0. Is there any  format of the pictures' names or sth else required? Looking forward to your reply.

**Comment by johncai117** [comment]
Hi, could you give more details on the issue that you face?

The key thing to do is to replicate the class of the data loaders in the dataset folder

**Comment by haprine** [comment]
Yeah, I replicated the CropDisease_few_shot.py and replace the 'CropDisease' with the name of my own dataset.  And I checked the data loaders again and I think where the problem is. Thank you so much :)
